require: rubocop-rails

Style/StringLiterals:
  EnforcedStyle: double_quotes

Documentation:
  Enabled: false

# temporary
Layout/LineLength:
  Max: 150

Style/FrozenStringLiteralComment:
  Enabled: false

# temporary
Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Enabled: false

Rails/FilePath:
  Enabled: false

Metrics/ClassLength:
  Max: 150

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - test/**/*
    # - db/schema.rb
    # - db/migrate/*
    # - bin/*
