default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/dev.db

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: mysql2
  url: <%= ENV['DATABASE_URL'] %>
